# Welcome to Jekyll!

# Basic Site Settings
locale         : "en-US"
title          : "Vivian Juehui Zheng"
title_separator: "-"
name           : "Vivian Juehui Zheng"
description    : "Ph.D. Candidate in Economics at UC Santa Cruz, specializing in behavioral and experimental economics."
url            : "https://vivianzvz.github.io"
baseurl        : ""
repository     : "vivianzvz/vivianzvz.github.io"

# Site Author
author:
  avatar    : "VivianZheng2.JPG"
  name      : "Vivian Juehui Zheng"
  pronouns  : "she/her"
  bio       : "Ph.D. Candidate in Economics at UC Santa Cruz. I use experiments and behavioral models to study how people make decisions in markets."
  location  : "Santa Cruz, California"
  employer  : "University of California, Santa Cruz"
  uri       : "https://vivianjzheng.com"
  email     : "vjzheng@ucsc.edu"

  # Repositories and software development
  github    : "vivianzvz"

  # Social media
  instagram : "vivianzvz"
  linkedin  : "vivianjzheng"

# Site Settings
teaser:                     
breadcrumbs: false
words_per_minute: 160
future: true
read_more: "disabled"
talkmap_link: false

# Comments
comments:
  provider: false
  disqus:
    shortname: 
  discourse:
    server: 
  facebook:
    appid: 
    num_posts: 
    colorscheme: 

# Atom/RSS feed
atom_feed:
  hide: false
  path: 

# SEO
google_site_verification:
bing_site_verification:
alexa_site_verification:
yandex_site_verification:

# Social Sharing
twitter:
  username: "vivianjzheng"
facebook:
  username:
  app_id:
  publisher:
og_image: "/images/profile.png"
social:
  type: Person
  name: Vivian Juehui Zheng
  links:
    - "https://www.linkedin.com/in/vivianjzheng/"
    - "https://github.com/vivianzvz"
    - "https://www.instagram.com/vivianjzheng/"

# Analytics
analytics:
  provider: "false"
  google:
    tracking_id: 

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: America/Los_Angeles

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
